apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-pv
spec:
  storageClassName: "local-path"
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: order-pvc
    namespace: eatfresh
  hostPath:
    path: "/mnt/data/sqlserver"