apiVersion: v1
kind: Service
metadata:
  name: table-service
  namespace: eatfresh
spec:
  type: ClusterIP
  selector:
    app: tablebooking
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4000
