apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: eatfresh
  labels:
    app: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: registry.gitlab.au.dk/wao-exercises1/eatfresh/eatfresh.apigateway:latest
        ports:
        - containerPort: 5000
        env:
        - name: REL_URL_PATH
          valueFrom:
            configMapKeyRef:
              name: gateway-config
              key: REL_URL_PATH
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
      imagePullSecrets:
      - name: my-registry-credentials
