apiVersion: v1
kind: ConfigMap
metadata:
  name: menu-config
  namespace: eatfresh
data:
  appsettings.json: |-
    {
      "ConnectionStrings": {
        "DefaultConnection": "Server=menu-sql-service,1432;Database=master;User=sa;Password=<YourStrong@Passw0rd>;TrustServerCertificate=True"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*"
    }
  rel_url_path: "/grp-13/webmenuapi"
