apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app-deployment
  namespace: eatfresh
  labels:
    app: weborder-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weborder-pod
  template:
    metadata:
      labels:
        app: weborder-pod
    spec:
      containers:
      - name: weborder
        image: registry.gitlab.au.dk/wao-exercises1/eatfresh/eatfresh.orderprocessing:0.0.15.v
        ports:
        - containerPort: 5126
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ACCEPT_EULA
          valueFrom:
            secretKeyRef:
              name: order-sql-secret
              key: ACCEPT_EULA
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: order-sql-secret
              key: SA_PASSWORD       
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        volumeMounts:
        - name: config-volume-order
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: config-volume-order
        configMap:
          name: order-config
      imagePullSecrets:
      - name: my-registry-credentials
