apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: eatfresh
spec:
  type: ClusterIP
  selector:
    app: weborder-pod
  ports:
    - protocol: TCP
      port: 5051
      targetPort: 5126