apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: eatfresh
spec:
  selector:
    app: webapi-order
  ports:
    - name: port1
      protocol: TCP
      port: 80
      targetPort: 5126
  type: ClusterIP
