apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: eatfresh
  labels:
    app: webapi-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi-order
  template:
    metadata:
      labels:
        app: webapi-order
    spec:
      containers:
      - name: webapi-order
        image: registry.gitlab.au.dk/wao-exercises1/eatfresh/eatfresh.orderprocessing:0.0.07.v
        ports:
        - containerPort: 5126
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ACCEPT_EULA
          valueFrom:
            secretKeyRef:
              name: order-db-secret  # Correct secret name
              key: ACCEPT_EULA
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: order-db-secret  # Correct secret name
              key: SA_PASSWORD
        - name: RABBITMQ_HOST
          value: rabbitmq.eatfresh.svc.cluster.local
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: guest
        - name: RABBITMQ_PASS
          value: guest
        resources:
          requests:
            cpu: "150m"
            memory: "64Mi"
          limits:
            cpu: "600m"
            memory: "128Mi"
        volumeMounts:
        - name: config-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: config-volume
        configMap:
          name: order-config
      imagePullSecrets:
      - name: my-registry-credentials
