apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: eatfresh
spec:
  selector:
    app: weborder-pod
  ports:
    - name: port1
      protocol: TCP
      port: 5051
      targetPort: 5126
  type: ClusterIP