apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: eatfresh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordersqlserver
  template:
    metadata:
      labels:
        app: ordersqlserver
    spec:
      containers:
      - name: ordersqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: order-sql-secret
              key: SA_PASSWORD
        - name: MSSQL_PID
          value: "Express"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: order-sqlstorage
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: order-sqlstorage
        persistentVolumeClaim:
          claimName: order-sql-pvc
