apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-sql-pvc
  namespace: eatfresh
spec:
  storageClassName: "local-path"
  volumeName: order-sql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
