apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-volume-pv
spec:
  storageClassName: "local-path"
  capacity:
    storage: 512Mi  
  #volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: eatfresh
    name: mongo-volume-pvc
  hostPath:
    path: "/slet/"
