apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-pv
spec:
  storageClassName: "local-path"
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/mnt/data/sqlserver"
  claimRef:
    namespace: eatfresh
    name: sql-pvc
