apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: menu-pvc
  namespace: eatfresh
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi